### ISSUE TITLE
Test failing

### ISSUE THREAD

**Issue by ryannealmes** [getsmarter/moodle-api#12]
The latest version of JSON.parse is return `nil` instead of `"null"`.

Checking if it's meant to do this before I update the test.

**Comment by ryannealmes** [comment]
To replicate

```ruby
2.3.0 :001 > gem 'json', '2.0.2'
 => true
2.3.0 :002 > require 'json'
 => true
2.3.0 :003 > JSON.parse("null")
 => nil

----------------------------------------------------------------------

2.3.0 :001 > gem 'json', '1.8.3'
 => true
2.3.0 :003 > require 'json'
 => true
2.3.0 :004 > JSON.parse("null")
JSON::ParserError: 784: unexpected token at 'null'
  from /Users/ryannealmes/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
  from /Users/ryannealmes/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
  from (irb):4
  from /Users/ryannealmes/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
2.3.0 :005 >
```

**Comment by ryannealmes** [comment]
https://github.com/flori/json/issues/299

**Comment by ryannealmes** [comment]
I managed to find an answer here, so I will update the test as it is expected functionality.

http://stackoverflow.com/questions/38669780/why-is-json-parse-not-throwing-exception
